payload:
  - DOMAIN-SUFFIX,awesome-hd.me
  - DOMAIN-SUFFIX,broadcasthe.net
  - DOMAIN-SUFFIX,chdbits.co
  - DOMAIN-SUFFIX,classix-unlimited.co.uk
  - DOMAIN-SUFFIX,empornium.me
  - DOMAIN-SUFFIX,gazellegames.net
  - DOMAIN-SUFFIX,hdchina.org
  - DOMAIN-SUFFIX,hdsky.me
  - DOMAIN-SUFFIX,icetorrent.org
  - DOMAIN-SUFFIX,jpopsuki.eu
  - DOMAIN-SUFFIX,keepfrds.com
  - DOMAIN-SUFFIX,madsrevolution.net
  - DOMAIN-SUFFIX,m-team.cc
  - DOMAIN-SUFFIX,nanyangpt.com
  - DOMAIN-SUFFIX,ncore.cc
  - DOMAIN-SUFFIX,open.cd
  - DOMAIN-SUFFIX,ourbits.club
  - DOMAIN-SUFFIX,passthepopcorn.me
  - DOMAIN-SUFFIX,privatehd.to
  - DOMAIN-SUFFIX,redacted.ch
  - DOMAIN-SUFFIX,springsunday.net
  - DOMAIN-SUFFIX,tjupt.org
  - DOMAIN-SUFFIX,totheglory.im
  - DOMAIN-KEYWORD,aria2
  - DOMAIN-KEYWORD,thunder
  - DOMAIN-KEYWORD,xlliveud
  - DOMAIN-KEYWORD,xunlei
  - DOMAIN-KEYWORD,yunpan
  - DOMAIN-KEYWORD,announce
  - DOMAIN-KEYWORD,torrent
  - DOMAIN-KEYWORD,tracker
  - PROCESS-NAME,aria2c
  - PROCESS-NAME,bitcomet
  - PROCESS-NAME,BitComet
  - PROCESS-NAME,downloadservice
  - PROCESS-NAME,fdm
  - PROCESS-NAME,folx
  - PROCESS-NAME,nettransport
  - PROCESS-NAME,NetTransport
  - PROCESS-NAME,qbittorrent
  - PROCESS-NAME,thunder
  - PROCESS-NAME,Thunder
  - PROCESS-NAME,transmission-daemon
  - PROCESS-NAME,transmission-qt
  - PROCESS-NAME,utorrent
  - PROCESS-NAME,uTorrent
  - PROCESS-NAME,webtorrent
  - PROCESS-NAME,WebTorrent
  - PROCESS-NAME,Folx
  - PROCESS-NAME,NetTransport
  - PROCESS-NAME,qbittorrent
  - PROCESS-NAME,Thunder
  - PROCESS-NAME,Transmission
  - PROCESS-NAME,transmission
  - PROCESS-NAME,WebTorrent Helper
  - PROCESS-NAME,webtorrenthelper
  - PROCESS-NAME,v2ray
  - PROCESS-NAME,ss-local
  - PROCESS-NAME,ssr-local
  - PROCESS-NAME,ss-redir
  - PROCESS-NAME,ssr-redir
  - PROCESS-NAME,ss-server
  - PROCESS-NAME,trojan-go
  - PROCESS-NAME,xray
  - PROCESS-NAME,hysteria
  - PROCESS-NAME,UUBooster
  - PROCESS-NAME,uugamebooster
  - PROCESS-NAME,weiyun
  - DOMAIN-SUFFIX,smtp
