payload:
# > name
  - PROCESS-NAME,emby
  - PROCESS-NAME,emby.theater.exe
  - PROCESS-NAME,electron
  - PROCESS-NAME,electron.exe
# > Plus
  - DOMAIN,emby.plusmedia.site
  - DOMAIN,emby-cf.plusmedia.site
  - DOMAIN,emby.xeton.dev
  - DOMAIN,jellyfin.xeton.dev
  - DOMAIN,movie.xeton.dev
