payload:
# > KEYWORD
#  - DOMAIN-KEYWORD,emby
# > plus
  - DOMAIN-SUFFIX,plusmedia.site
  - DOMAIN-SUFFIX,xeton.dev
# > pr
  - DOMAIN,emby.prprcloud.com
  - DOMAIN,prpr.kyarucloud.moe
# > mx
  - DOMAIN,embyclub.com
# > ms
  - DOMAIN-SUFFIX,aaa.ax
# > cr
  - DOMAIN,play.charontv.com
