payload:
# > KEYWORD
#  - DOMAIN-KEYWORD,emby
# > plus
  - DOMAIN-SUFFIX,plusmedia.site
  - DOMAIN-SUFFIX,xeton.dev
# > pr
  - DOMAIN-SUFFIX,prprcloud.com
  - DOMAIN-SUFFIX,kyarucloud.moe
# > mx
  - DOMAIN,embyclub.com
# > ms
  - DOMAIN-SUFFIX,aaa.ax
# > cr
  - DOMAIN-SUFFIX,charontv.com
