payload:
# > keyword
  - DOMAIN-KEYWORD,emby
  - DOMAIN-KEYWORD,xeton.dev
  - DOMAIN-KEYWORD,kyarucloud.moe
  - DOMAIN-KEYWORD,ssky.me
  - DOMAIN-KEYWORD,embyclub.com
# > name
  - PROCESS-NAME,emby
  - PROCESS-NAME,emby.theater.exe
  - PROCESS-NAME,electron
  - PROCESS-NAME,electron.exe
# > nexitally
  - DOMAIN-SUFFIX,emby.nexitally.com
# > prpr
  - DOMAIN-SUFFIX,emby.prprcloud.com
# > kyaru
  - DOMAIN-SUFFIX,prpr.kyarucloud.moe
# > haochi
  - DOMAIN-SUFFIX,public.kyarucloud.moe
# > emby-misty
  - DOMAIN-SUFFIX,emby.ssky.me
  - DOMAIN-SUFFIX,emby-cf.ssky.me
# > maoxiong
  - DOMAIN-SUFFIX,embyclub.com
  - DOMAIN-SUFFIX,aws-hk.embyclub.com
  - DOMAIN-SUFFIX,aga-jp.embyclub.com
  - DOMAIN-SUFFIX,az-hk.embyclub.com
  - DOMAIN-SUFFIX,azsgp.embyclub.com
# > Plus
  - DOMAIN-SUFFIX,emby.plusmedia.site
  - DOMAIN-SUFFIX,emby-cf.plusmedia.site 
  - DOMAIN-SUFFIX,emby.xeton.dev
  - DOMAIN-SUFFIX,jellyfin.xeton.dev
  - DOMAIN-SUFFIX,movie.xeton.dev
