payload:
  - DOMAIN,ad.10010.com
  - DOMAIN,analytics.95516.com
  - DOMAIN,analytics.strava.com
  - DOMAIN,app.adjust.com
  - DOMAIN,bdtj.tagtic.cn
  - DOMAIN,errlog.umeng.com
  - DOMAIN,fairplay.l.qq.com
  - DOMAIN,fonts.gstatic.com
  - DOMAIN,log.mmstat.com
  - DOMAIN,msg.umeng.com
  - DOMAIN,msg.umengcloud.com
  - DOMAIN,origin-a.akamaihd.net
  - DOMAIN,picanalysis.vivo.com.cn
  - DOMAIN,sycm.mmstat.com
  - DOMAIN,tracking.miui.com
  - DOMAIN,vi.l.qq.com
  - DOMAIN,xivanalysis.com
  - DOMAIN,els.ztgame.com
  - DOMAIN-SUFFIX,dizhensubao.getui.com
  - DOMAIN-SUFFIX,f.video.weibocdn.com
  - DOMAIN-SUFFIX,fus.cdn.krcom.cn
  - DOMAIN-SUFFIX,ol.epicgames.com
  - DOMAIN-SUFFIX,tracking-protection.cdn.mozilla.net
  - DOMAIN-KEYWORD,wb_ad
